syntax = "proto3";

package ai;

option go_package = "github.com/noirbyss/worktrition-app/gen/ai-service;ai";

service AiService {
    rpc StartGeneration(StartGenerationRequest) returns (StartGenerationResponse);
    
    rpc GetGenerationStatus(GetGenerationStatusRequest) returns (GetGenerationStatusResponse);
}

message StartGenerationRequest {
    string user_id = 1;
    
    bool generate_workout = 2; // Если true, генерируем зал
    bool generate_nutrition = 3; // Если true, генерируем еду
}

message StartGenerationResponse {
    // Возвращаем ID, чтобы клиент мог по нему спрашивать статус
    string generation_id = 1;
}

message GetGenerationStatusRequest {
    string generation_id = 1;
}

enum GenerationStatus {
    GENERATION_STATUS_UNSPECIFIED = 0;
    GENERATION_STATUS_PENDING = 1; // Еще думает
    GENERATION_STATUS_DONE = 2;    // Готово!
    GENERATION_STATUS_FAILED = 3;  // Ошибка (нейросеть упала)
}

message GetGenerationStatusResponse {
    GenerationStatus status = 1;
}