syntax = "proto3";

package nutrition;

option go_package = "github.com/noirbyss/worktrition-app/gen/nutrition-service;nutrition";

import "google/protobuf/empty.proto";

enum DaysOfWeek {
    DAYS_OF_WEEK_UNSPECIFIED = 0;
    DAYS_OF_WEEK_MONDAY = 1;
    DAYS_OF_WEEK_TUESDAY = 2;
    DAYS_OF_WEEK_WEDNESDAY = 3;
    DAYS_OF_WEEK_THURSDAY = 4;
    DAYS_OF_WEEK_FRIDAY = 5;
    DAYS_OF_WEEK_SATURDAY = 6;
    DAYS_OF_WEEK_SUNDAY = 7;
}

message NutritionFacts {
    double calories = 1;
    double protein = 2;
    double fat = 3;
    double carb = 4;
}

service NutritionService {
    rpc SaveGeneratedPlan(SaveGeneratedPlanRequest) returns (google.protobuf.Empty);
    rpc GetDayPlan(GetDayPlanRequest) returns (GetDayPlanResponse);
    rpc CompleteMeal(CompleteMealRequest) returns (google.protobuf.Empty);
    rpc CompleteWater(CompleteWaterRequest) returns (google.protobuf.Empty);
    rpc GetStats(GetStatsRequest) returns (GetStatsResponse);
}

message MealItemsRequest {
    string name = 1;
    string recipe = 2;
    NutritionFacts nutrition_facts = 3;
}

message PlannedMealsRequest {
    DaysOfWeek day_of_week = 1;
    repeated MealItemsRequest meal_items = 2;
    NutritionFacts nutrition_facts = 3;
}

message SaveGeneratedPlanRequest {
    string user_id = 1;
    string generation_id = 2;
    repeated PlannedMealsRequest planned_meals = 3;
    NutritionFacts nutrition_facts = 4;
    int32 water_goal_ml = 5;
}

message GetDayPlanRequest {
    string user_id = 1;
    DaysOfWeek day_of_week = 2;
}

message MealItemsResponse {
    int32 id = 1;
    string name = 2;
    string recipe = 3;
    NutritionFacts nutrition_facts = 4;
}

message GetDayPlanResponse {
    repeated MealItemsResponse meal_items = 1;
    NutritionFacts nutrition_facts = 2;
    int32 water_goal_ml = 3;
}

message CompleteMealRequest {
    string user_id = 1;
    int32 meal_item_id = 2;
}

message CompleteWaterRequest {
    string user_id = 1;
    int32 amount_ml = 2;
}

message GetStatsRequest {
    string user_id = 1;
}

message GetStatsResponse {
    double percentage_compliance_nutrition_facts = 1;
    double percentage_plan_fulfilled = 2;
    double percentage_water_standard_fulfillment = 3;
}