syntax = "proto3";

package workout;

option go_package = "github.com/noirbyss/worktrition-app/gen/workout-service;workout";

import "google/protobuf/empty.proto";

enum DaysOfWeek {
    DAYS_OF_WEEK_UNSPECIFIED = 0;
    DAYS_OF_WEEK_MONDAY = 1;
    DAYS_OF_WEEK_TUESDAY = 2;
    DAYS_OF_WEEK_WEDNESDAY = 3;
    DAYS_OF_WEEK_THURSDAY = 4;
    DAYS_OF_WEEK_FRIDAY = 5;
    DAYS_OF_WEEK_SATURDAY = 6;
    DAYS_OF_WEEK_SUNDAY = 7;
}

service WorkoutService {
    rpc SaveGeneratedPlan(SaveGeneratedPlanRequest) returns (google.protobuf.Empty);
    rpc GetDayPlan(GetDayPlanRequest) returns (GetDayPlanResponse);
    rpc CompleteTraining(CompleteTrainingRequest) returns (google.protobuf.Empty);
    rpc GetStats(GetStatsRequest) returns (GetStatsResponse);
}

message WorkoutDayRequest {
    DaysOfWeek day_of_week = 1;
    string type = 2;
    repeated string exercises = 3;
}

message SaveGeneratedPlanRequest {
    string user_id = 1;
    string generation_id = 2;
    repeated WorkoutDayRequest workout_days = 3;
}

message GetDayPlanRequest {
    string user_id = 1;
    DaysOfWeek day_of_week = 2;
}

message GetDayPlanResponse {
    DaysOfWeek day_of_week = 1;
    string type = 2;
    repeated string exercises = 3;
}

message CompleteTrainingRequest {
    string user_id = 1;
    DaysOfWeek day_of_week = 2;
    int32 duration_seconds = 3;
}

message GetStatsRequest {
    string user_id = 1;
}

message GetStatsResponse {
    double percentage_plan_fulfilled = 1;
    int32 current_streak_days = 2;
    int32 total_training_time_seconds = 3;
}
